[behave]
paths = features
#allows print() outputs to show in console
stdout_capture = false
stderr_capture = false
#useful for debugging selenium
log_capture = false
tags =  @Regression

[userdata]
env = qa
#headless = false
